title: Agency - Start Bootstrap Theme
description: ''
author: ''
url: "https://thenomadarchive.com"
baseurl: "/"
sass:
  style: compressed

assets_path: '' 

collections:
  projects:

theme: jekyll-theme-architect
